// this is used to create patterns for publications test with a direct insert, not the Meteor method
// it must be updated to include all pattern fields

export const defaultPatternData = {
	'createdAt': new Date('Tue, 03 Mar 2020 17:58:05 GMT'),
	'createdBy': 'abc',
	'description': 'Description of a pattern',
	'holeHandedness': 'clockwise',
	'holes': 4,
	'isPublic': false,
	'name': 'Pattern 1',
	'nameSort': 'pattern 1',
	'numberOfRows': 6,
	'numberOfTablets': 8,
	'orientations': ['\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\'],
	'palette': ['#fff'],
	'patternDesign': {},
	'patternType': 'individual',
	'previewOrientation': 'up',
	'tags': [],
	'threadingNotes': 'Some threading notes',
	'threading': [[1]],
	'weavingNotes': 'Some weaving notes',
	'weftColor': 2,
};

export const defaultColorBookData = {
	'_id': 'hGyoeA5tfZ4MuwfLj',
	'name': 'Another book',
	'nameSort': 'another book',
	'createdAt': new Date('Tue, 03 Mar 2020 17:58:05 GMT'),
	'createdBy': 'Mh27efDaNFq7xzPjB',
	'colors': [
		'#aa1122',
		'#aa2233',
		'#aa3344',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
		'#aa0000',
	],
	'isPublic': false,
};
